services:
 postgres:
  container_name: postgres
  image: postgres:latest
  ports:
   - 5432:5432
  environment:
   - POSTGRES_PASSWORD=postgres
  volumes:
   - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume:
    driver: local
